## 
### Travis Unit Testing settings
##

language: cpp

compiler:
  - clang

addons:
  apt:
    packages:
      - libboost-filesystem1.55-dev
      - libboost-test1.55-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ./nyx_testrunner

