## 
### Travis Unit Testing settings
##
sudo: false

language: cpp

compiler:
  - gcc

install:
- if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libboost-filesystem1.55-dev
      - libboost-system1.55-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ./nyx_testrunner
