## 
### Travis Unit Testing settings
##

language: cpp

compiler:
  - gcc 

addons:
  apt:
    packages:
      - libboost-filesystem-dev
      - libboost-system-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ./nyx_testrunner

