## 
### Travis Unit Testing settings
##
sudo: false

language: cpp

compiler:
  - gcc

install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-4.8" CC="gcc-4.8"; fi

env:
  - TBB_ROOT=/usr

addons:
  apt:
    sources:
      - boost-latest
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
      - libboost1.55-all-dev
      - libtbb-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make
  - ./nyx_testrunner
